
spring:
  datasource:
    url: jdbc:mysql://47.103.83.230:3306/mysql?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 2009@qazWSX
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: eureka-provider
server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapperxml/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8070/eureka/ #注册中心的注册地址

#elasticsearch 自定义配置
xiaomifeng1010:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200} #多个结点中间用逗号分隔